### ISSUE TITLE
3rd week peer to peer code review

### ISSUE THREAD

**Issue by sumon766** [sawmon71293/personal-portfolio#16]
You have done a great job, I must say it's excellent. There is a very minor change I would like to suggest to you. That is to add some left-side padding to the input items of your contact form and add some padding to all sides of the textarea element. This will make the form even more catchy.
![Screenshot](https://user-images.githubusercontent.com/22003499/215693540-51c75838-2075-4b87-8afc-3d1d878eba2c.png)

**Comment by supreeti** [comment]
you have done a great job but i suggest you to add a cursor as pointer to the hover of the button and transitions to the buttons.

**Comment by sawmon71293** [comment]
Thanks for your suggestions. It's very useful for me.

**Comment by bronnie313** [comment]
Your website is looking awesome, it reflects that you have worked a lot on this. Though I would like to suggest a small thing that you could make better. I think the margin/padding between the last post and the about section can be reduced. This will bring the content close and increase the beauty of the website. Check the screenshot below for a better understanding.

![](https://files.slack.com/files-pri/T47CT8XPG-F04M2SL90ES/screenshot_1_.png)
