### ISSUE TITLE
Peer to peer code review on mobile menu

### ISSUE THREAD

**Issue by torobucci** [sawmon71293/personal-portfolio#19]
Hi @sawmon71293 

Great job on the correct use of github workflow✔
Great use of html , css and javascript best practices✔

## [Optional Suggestions]
- I think it would be better to use a lesser transform scale on your [Portfolio](https://github.com/sawmon71293/personal-portfolio/blob/e67f9567506cc14c22994d224a14f89e643dae95/style.css#L311-L314) image so that it would not overlay on the project context. This makes your website more presentable.
- I suggest you also make the links on your mobile-menu to be active

![Capture](https://user-images.githubusercontent.com/103370560/217181847-639bbbf0-927a-4770-80d3-47b1820e2b80.PNG)

**Comment by sawmon71293** [comment]
Thanks for your respectful feedback.
