### ISSUE TITLE
Morning Session Code Review Feedback. 

### ISSUE THREAD

**Issue by ab-noori** [sawmon71293/personal-portfolio#7]
## Highlights
- Good usage of semantic tags.
- Implementation of CSS & HTML best pratices.
## Suggested Changes
- It would be better to use the anchor tag instead of the button "See Project" in the project section. https://github.com/sawmon71293/personal-portfolio/blob/519b90bba4f63e811b82af24b84dfeed596eebbb/index.html#L117
- It would be better not to comment on the unnecessary code inside your project. https://github.com/sawmon71293/personal-portfolio/blob/519b90bba4f63e811b82af24b84dfeed596eebbb/index.html#L238

**Comment by sawmon71293** [comment]
Thanks for giving me useful feedback.
